### ISSUE TITLE
Logs shouldn't contain admin password

### ISSUE THREAD

**Issue by OmgImAlexis** [daspanel/caddy-http-server#1]
Currently when a user boots daspanel for the first time the admin user/pass is added to the logs.
It's usually bad practise to leak any private info to logs.

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-00-daspanel-base: executing... 
[DASPANEL] INFO: Starting with UID 1000
[DASPANEL] DEFAULT: DASPANEL_SYS_HOST=daspanel.site
[DASPANEL] DEFAULT: DASPANEL_SYS_ADMIN=USERNAME_HERE
[DASPANEL] DEFAULT: DASPANEL_SYS_PASSWORD=PASSWORD_HERE
[cont-init.d] 00-00-daspanel-base: exited 0.
[cont-init.d] 00-20-ssmtp: executing... 
[cont-init.d] 00-20-ssmtp: exited 0.
[cont-init.d] 50-00-caddy: executing... 
[cont-init.d] 50-00-caddy: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Activating privacy features... done.
http://daspanel.site
http://admin.daspanel.site
http://api.daspanel.site
http://s3.svc.daspanel.site
http://mail.svc.daspanel.site
http://adminer.svc.daspanel.site
```

**Comment by admindaspanel** [comment]
Problem solved.

As the container that was generating the problem was [alpine-base](https://github.com/daspanel/alpine-base) all other images had to be updated. To download the current version of all Daspanel containers run the following command in the directory where the docker-compose.yml file is located:

`docker-compose down`
`docker-compose pull`
`docker-compose up -d`

The docker-compose pull command download new versions of the images used in the docker-compose.yml file, but on my computer left previous versions of the images without the latest tag. To remove the old images:

1. Use `docker-compose down  --rmi all` instead of `docker-compose down`

2. or, after getting the new images run `docker rmi $(docker images | grep "^<none>" | awk "{print $3}")` - CAUTION: this will remove all local untagged docker images even if not created by Daspanel.

**Comment by OmgImAlexis** [comment]
Looks like there's now an issue with the panel container. I'm also getting a 502 on the caddy server.

```
Traceback (most recent call last):
  File "/opt/daspanel/apps/panel/wsgi.py", line 3, in <module>
    app = create_app()
  File "/opt/daspanel/apps/panel/daspanel_web/__init__.py", line 33, in create_app
    app.config.from_object('config')
  File "/usr/lib/python2.7/site-packages/flask/config.py", line 168, in from_object
    obj = import_string(obj)
  File "/usr/lib/python2.7/site-packages/werkzeug/utils.py", line 418, in import_string
    __import__(import_name)
  File "/opt/daspanel/apps/panel/config.py", line 25, in <module>
    sys_config = json.loads(open(conf_file).read())
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by admindaspanel** [comment]
Could you send me the contents of the file `data/<UUID>/db/sysconfig.json` ?

Of course, change any confidential information before sending it.

**Comment by admindaspanel** [comment]
Due to an error in the automatic generation of the container images in hub.docker.com it will be necessary to update the following images again:

daspanel/api-server
daspanel/panel

**Comment by OmgImAlexis** [comment]
That file is completely empty. Guessing there's something I did wrong here.

Before commenting I ran this.
```
docker-compose down --rmi all
docker-compose pull
docker-compose up -d
```

**Comment by admindaspanel** [comment]
I think not, it must be a bug in the initialization scripts. While I do not find out the real reason for the problem, please delete the sysconfig.json file and restart Daspanel again. Let's me know If Its Works.

**Comment by admindaspanel** [comment]
@OmgImAlexis I updated the images of the containers and I think I solved the startup problems that happened to you. Please update your Daspanel images with the commands below and try again.

```
docker-compose down --rmi all
docker-compose pull
docker-compose up -d
```

**Comment by OmgImAlexis** [comment]
Looks like everything's working again.
